apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ercankurtoglu-xyz-tls
spec:
  secretName: ercankurtoglu-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ercankurtoglu.xyz
  dnsNames:
    - ercankurtoglu.xyz
    - www.ercankurtoglu.xyz