name: CI/CD with GKE

on:
  push:
    branches: [ master ]

env:
  SHA: ${{ github.sha }}
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Download gcloud SDK and install
      - name: Download Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null

      # Configure gcloud path
      - name: Configure Google Cloud SDK path
        run: echo "source $HOME/google-cloud-sdk/path.bash.inc"

      # Install kubectl and update
      - name: Install kubectl
        run: gcloud components update kubectl

      - name: Decrypt service account key
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PASSPHRASE }}" --output service-account.json service-account.json.gpg

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      # Set project and zone
      - name: Set project ID
        run: gcloud config set project multi-k8s-445712

      - name: Set compute zone
        run: gcloud config set compute/zone us-central1-a

      # Get cluster credentials
      - name: Get cluster credentials
        run: gcloud container clusters get-credentials multi-cluster

      # Login to Docker registry
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build test image
      - name: Build test image
        run: docker build -t ercankurtoglu/react-test -f ./client/Dockerfile.dev ./client

      # Run tests
      - name: Run tests
        run: docker run -e CI=true ercankurtoglu/react-test npm test

      # Build container images with tags
      - name: Build container images
        run: |
          docker build -t ercankurtoglu/multi-client:latest -t ercankurtoglu/multi-client:$SHA -f ./client/Dockerfile ./client
          docker build -t ercankurtoglu/multi-server:latest -t ercankurtoglu/multi-server:$SHA -f ./server/Dockerfile ./server
          docker build -t ercankurtoglu/multi-worker:latest -t ercankurtoglu/multi-worker:$SHA -f ./worker/Dockerfile ./worker

      # Push container images
      - name: Push container images
        run: |
          docker push ercankurtoglu/multi-client:latest
          docker push ercankurtoglu/multi-server:latest
          docker push ercankurtoglu/multi-worker:latest
          docker push ercankurtoglu/multi-client:$SHA
          docker push ercankurtoglu/multi-server:$SHA
          docker push ercankurtoglu/multi-worker:$SHA

      # Apply Kubernetes configurations
      - name: Apply Kubernetes configurations
        run: kubectl apply -f k8s

      # Update deployments with image tags
      - name: Update server deployment image
        run: kubectl set image deployments/server-deployment server=ercankurtoglu/multi-server:$SHA

      - name: Update client deployment image
        run: kubectl set image deployments/client-deployment client=ercankurtoglu/multi-client:$SHA

      - name: Update worker deployment image
        run: kubectl set image deployments/worker-deployment worker=ercankurtoglu/multi-worker:$SHA