name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  SHA: ${{ github.sha }}
  CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Decrypt service account key
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PASSPHRASE }}" --output service-account.json service-account.json.gpg

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      - name: Configure Google Cloud
        run: |
          gcloud config set project multi-k8s-445712
          gcloud config set compute/zone us-central1-a
          gcloud container clusters get-credentials multi-cluster

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build test image
        run: docker build -t ercankurtoglu/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true ercankurtoglu/react-test npm test

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Decrypt service account key
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PASSPHRASE }}" --output service-account.json service-account.json.gpg

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure Google Cloud
        run: |
          gcloud config set project multi-k8s-445712
          gcloud config set compute/zone us-central1-a
          gcloud container clusters get-credentials multi-cluster --zone us-central1-a --project multi-k8s-445712

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ercankurtoglu/multi-client:latest -t ercankurtoglu/multi-client:$SHA -f ./client/Dockerfile ./client
          docker build -t ercankurtoglu/multi-server:latest -t ercankurtoglu/multi-server:$SHA -f ./server/Dockerfile ./server
          docker build -t ercankurtoglu/multi-worker:latest -t ercankurtoglu/multi-worker:$SHA -f ./worker/Dockerfile ./worker
          docker push ercankurtoglu/multi-client:latest
          docker push ercankurtoglu/multi-server:latest
          docker push ercankurtoglu/multi-worker:latest
          docker push ercankurtoglu/multi-client:$SHA
          docker push ercankurtoglu/multi-server:$SHA
          docker push ercankurtoglu/multi-worker:$SHA

      - name: Apply Kubernetes configurations
        run: kubectl apply -f k8s

      - name: Update Kubernetes deployments
        run: |
          kubectl set image deployments/server-deployment server=ercankurtoglu/multi-server:$SHA
          kubectl set image deployments/client-deployment client=ercankurtoglu/multi-client:$SHA
          kubectl set image deployments/worker-deployment worker=ercankurtoglu/multi-worker:$SHA